"""added index

Revision ID: 3ce1b21d7686
Revises: 10f48acccb80
Create Date: 2021-12-09 12:04:44.305944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ce1b21d7686'
down_revision = '10f48acccb80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('devices_dev_id_dev_type_index', 'device', ['dev_id', 'dev_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('devices_dev_id_dev_type_index', table_name='device')
    # ### end Alembic commands ###
